from views_admin import *
from views_local import *
from views_habitacion import *
from views_punto import *
from views_cliente import *
from views_tipo import *
from views_producto import *
from views_plato import *
from views_user import *
